### ISSUE TITLE
Overriding the HTML page during enrollment doesn't work unless ProgressScreen is already open

### ISSUE THREAD

**Issue by rougegoat** [loceee/OSXCasperScripts#5]
Our policy is set to place the ProgressScreen.app file and the HTML file we're overriding it with and then immediately run this python script.  The script correctly sets the build time, hidden status for the quit button, etc.  However, it will not change the page pulled up until you run the script with the exact same settings a second time.  Once it's run that second time, it updates the page to show the HTML file we're overriding the default with.

The most annoying thing about this issue is that it only happens on enrollment.  The exact same policy put in Self Service works perfectly everytime.

**Comment by rougegoat** [comment]
Here's what the log  for the policy in Casper says 

> Running script COE - Progress Screen Helper...
Script exit code: 1
Script result: 32:104: execution error: An error of type -10810 has occurred. (-10810)
Traceback (most recent call last):
File "/Library/Application Support/JAMF/tmp/COE - Progress Screen Helper", line 145, in 
main()
File "/Library/Application Support/JAMF/tmp/COE - Progress Screen Helper", line 105, in main
subprocess.check_output(osa_full_command)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['osascript', '-e', 'tell application "ProgressScreen"', '-e', 'set htmlURL of every configuration to "/LAPS_Picture/Untitled-1.html"', '-e', 'end tell']' returned non-zero exit status 1
Error running script: return code was 1.
